# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: A Survival Guide to Software Development
author: Buckley Ross
copyright: '2021'
logo: assets/logo.png

# Information about where the book exists on the web
repository:
  url: https://github.com/buck-ross/survival-guide  # Online location of your book
  path_to_book: index  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: assets/favicon.ico
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
  extra_footer: |
    <center>
    Permission is granted to copy, distribute and/or modify this<br/>
    document under the terms of the GNU Free Documentation License,<br/>
    Version 1.3 or any later version published by the Free Software<br/>
    Foundation; with no Invariant Sections, no Front-Cover Texts, and<br/>
    no Back-Cover Texts.  A copy of the license is included in the<br/>
    section entitled "GNU Free Documentation License".
    </center>
